name: TypeDoc

on:
  push:
    branches:
      - master
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install dependencies ğŸ“¦
      - run: npm install

      - name: Build Library ğŸ› 
      - run: npm run build
      
      - name: Run Tests ğŸ§
      - run: npm run test

      - name: Run Linter ğŸ—
      - run: npm run lint

      - name: Run Prettier ğŸ’„
      - run: npm run check-format

      - name: Build Documentation ğŸ“–
        run: npm run docs

      - name: Deploy Documentation ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs
